CREATE TABLE IF NOT EXISTS `workorder_form` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `username` text NOT NULL,
  `email` text NOT NULL,
  `date` text NOT NULL,
  `department` text NOT NULL,
  `role` text NOT NULL,
  `be_depart` text NOT NULL,
  `be_role` text NOT NULL,
  `be_role2` text NOT NULL,
  `type` text NOT NULL,
  `description` text NOT NULL,
  `amount` text NOT NULL,
  `category` text NOT NULL,
  `m_date_time` text NOT NULL,
  `closeout` text NOT NULL,
  `closeout_date` text NOT NULL,
  `head_status` text NOT NULL,
  `head_msg` text NOT NULL,
  `head_date` text NOT NULL,
  `engineering_status` text NOT NULL,
  `engineering_msg` text NOT NULL,
  `eng_date` text NOT NULL,
  `reason` text NOT NULL,
  `finance_status` text NOT NULL,
  `finance_msg` text NOT NULL,
  `fc_date` text NOT NULL,
  `ceo_status` text NOT NULL,
  `ceo_msg` text NOT NULL,
  `status` text NOT NULL,
  `task_status` text NOT NULL,
  `final_remarks` text NOT NULL,
  `final_status` text NOT NULL,
  `depart_type` text NOT NULL,
  `admin_status` text NOT NULL,
  `admin_msg` text NOT NULL,
  `admin_date` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `workorder_action_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `request_id` int(11) NOT NULL,
  `action_stage` varchar(50) NOT NULL,
  `action_name` varchar(50) NOT NULL,
  `actor_name` varchar(255) DEFAULT '',
  `actor_username` varchar(255) DEFAULT '',
  `actor_role` varchar(255) DEFAULT '',
  `note` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_workorder_action_log_request` (`request_id`),
  KEY `idx_workorder_action_log_stage` (`action_stage`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `workorder_mail_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `request_id` int(11) DEFAULT NULL,
  `mail_to` text DEFAULT NULL,
  `subject` varchar(255) DEFAULT '',
  `delivery_status` varchar(50) NOT NULL,
  `note` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_workorder_mail_log_request` (`request_id`),
  KEY `idx_workorder_mail_log_status` (`delivery_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
